// One-time setup for the browser UI: fresh demo mint (faucet-controlled) + a fresh
// open fixture with a 7-day lock window on the deployed 6krd program.
// Emits app/ui/config.js for the static page.
import * as anchor from "@coral-xyz/anchor";
import { Program, BN } from "@coral-xyz/anchor";
import { Keypair, PublicKey, SystemProgram } from "@solana/web3.js";
import { createMint, getAssociatedTokenAddressSync, TOKEN_PROGRAM_ID, ASSOCIATED_TOKEN_PROGRAM_ID } from "@solana/spl-token";
import PpIdl from "./player_perps.idl.json";
import { DEFAULT_DIST_PARAMS, DEFAULT_PAYOUT_PARAMS } from "./engine.ts";
import * as fs from "fs";

const FIXTURE_ID = 90000001; // UI demo fixture (not a TxLine id — staking/lifecycle demo only)
const UI_DIR = process.env.HOME + "/Player and match score perps/app/ui";

async function main() {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);
  const keeper = (provider.wallet as anchor.Wallet).payer;
  const pp = new Program(PpIdl as anchor.Idl, provider);

  // Faucet keypair = mint authority of the demo USDC. DEVNET-ONLY: its secret ships
  // in the page so any visitor can mint their stake. Never do this with a real token.
  const faucet = Keypair.generate();
  const usdcMint = await createMint(provider.connection, keeper, faucet.publicKey, null, 6);
  console.log("demo USDC mint:", usdcMint.toBase58(), "| faucet:", faucet.publicKey.toBase58());

  const idBuf = new BN(FIXTURE_ID).toArrayLike(Buffer, "le", 8);
  const [fixturePda] = PublicKey.findProgramAddressSync([Buffer.from("fixture"), idBuf], pp.programId);
  const escrow = getAssociatedTokenAddressSync(usdcMint, fixturePda, true);

  const lockTime = Math.floor(Date.now() / 1000) + 7 * 86400;
  const D = DEFAULT_DIST_PARAMS, P = DEFAULT_PAYOUT_PARAMS;
  await pp.methods.initializeFixture(new BN(FIXTURE_ID), new BN(lockTime),
    { p: new BN(D.p), wGd: new BN(D.wGd), wTg: new BN(D.wTg), wCs: new BN(D.wCs), capGd: D.capGd, capTg: D.capTg },
    { gamma: P.gamma, takeRateBps: P.takeRateBps, capMultiple: new BN(P.capMultiple) })
    .accountsStrict({ authority: keeper.publicKey, fixture: fixturePda, usdcMint, escrow,
      tokenProgram: TOKEN_PROGRAM_ID, associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID, systemProgram: SystemProgram.programId })
    .rpc();
  console.log("✓ fixture", FIXTURE_ID, "initialized:", fixturePda.toBase58(), "| lock:", new Date(lockTime * 1000).toISOString());

  const cfg = `// AUTO-GENERATED by setup-ui-fixture.ts — devnet demo config.
// FAUCET_SECRET is intentionally public: it only mints the worthless demo token. DEVNET ONLY.
window.PP_CONFIG = {
  RPC: "https://api.devnet.solana.com",
  PROGRAM_ID: "${pp.programId.toBase58()}",
  USDC_MINT: "${usdcMint.toBase58()}",
  FIXTURE_ID: ${FIXTURE_ID},
  FIXTURE_PDA: "${fixturePda.toBase58()}",
  ESCROW: "${escrow.toBase58()}",
  LOCK_TIME: ${lockTime},
  FAUCET_SECRET: [${Array.from(faucet.secretKey).join(",")}],
};\n`;
  fs.writeFileSync(`${UI_DIR}/config.js`, cfg);
  fs.writeFileSync("/tmp/ui-faucet.json", JSON.stringify(Array.from(faucet.secretKey)));
  console.log("✓ wrote", `${UI_DIR}/config.js`);
}
main().catch((e) => { console.error("SETUP FAILED:", e?.error?.errorMessage ?? e?.message ?? e); process.exit(1); });
